<div class="alert alert-success" data-title="">
  <h2><i class="fa fa-tasks" aria-hidden="true"></i> 2016년 서울시 수질데이터를 사용해 보기
  </h2>
</div>

In [12]:
import pandas as pd
import numpy as np

raw_data = pd.read_csv('../../data/water.csv', 
                       encoding='CP949', # encoding problem utf-8
                       engine='python')
raw_data.head()

   연번 약수터명  동명 총대장균군  일반세균  질산성질소   적합
0   1   백수  모라   양 성  10.0    6.7  부적합
1   2   이칠  모라   음 성  20.0    0.9   적합
2   3  운수사  모라   음 성  10.0    1.1   적합
3   4  서당골  모라   음 성  10.0    NaN   적합
4   5   청수  괘법   음 성  20.0    2.7   적합

In [13]:
# 적합한 데이터만 가져온것
tmp = raw_data[raw_data['적합'] == '적합']
tmp.pivot_table(index = '약수터명',
               aggfunc = 'mean',
               values=['일반세균', '질산성질소'])

      일반세균  질산성질소
약수터명
거북    20.0    1.0
건강    10.0    1.8
괘내    20.0    3.1
백양정   10.0    7.5
복천    20.0    2.4
불심    20.0    1.7
사상    10.0    2.2
삼각산   10.0    2.7
삼운정   20.0    3.8
서당골   10.0    NaN
승학    20.0    2.6
운수사   10.0    1.1
이칠    20.0    0.9
청수    20.0    2.7
체육공원  20.0    4.0
황씨묘위  10.0    3.1

In [14]:
raw_data = raw_data.interpolate(method='linear', axis=0, limit_direction='both')

In [15]:
raw_data

    연번  약수터명  동명 총대장균군   일반세균  질산성질소   적합
0    1    백수  모라   양 성   10.0    6.7  부적합
1    2    이칠  모라   음 성   20.0    0.9   적합
2    3   운수사  모라   음 성   10.0    1.1   적합
3    4   서당골  모라   음 성   10.0    1.9   적합
4    5    청수  괘법   음 성   20.0    2.7   적합
5    6    사상  괘법   음 성   10.0    2.2   적합
6    7    탑골  괘법   양 성   10.0    2.6  부적합
7    8   삼각산  괘법   음 성   10.0    2.7   적합
8    9    괘내  괘법   음 성   20.0    3.1   적합
9   10  황씨묘위  감전   음 성   10.0    3.1   적합
10  11  체육공원  감전   음 성   20.0    4.0   적합
11  12    건강  주례   음 성   10.0    1.8   적합
12  13   백양골  주례   양 성   10.0    2.8  부적합
13  14   백양정  주례   음 성   10.0    7.5   적합
14  15   승록정  주례   음 성   20.0    2.3  부적합
15  16    복천  주례   음 성   20.0    2.4   적합
16  17    밤골  주례   음 성   20.0    3.1   적합
17  18   삼운정  주례   음 성   20.0    3.8   적합
18  19    무명  주례   음 성  110.0    0.7  부적합
19  20    승학  학장   양 성   65.0    0.3  부적합
20  21    거북  학장   음 성   20.0    1.0   적합
21  22    백련  엄궁   양 성   40.0    1.9  부적합
22  23    불심  엄궁   음 성   20.0    1.7   적합
23  24    승학  엄궁   음 성   20.0    2.6   적합

In [16]:
raw_data['적합'] = raw_data['적합'].map({'부적합':0 ,'적합':1})
raw_data['총대장균군'] = raw_data['총대장균군'].map({'음 성':0 ,'양 성':1})

In [17]:
raw_data

    연번  약수터명  동명  총대장균군   일반세균  질산성질소  적합
0    1    백수  모라      1   10.0    6.7   0
1    2    이칠  모라      0   20.0    0.9   1
2    3   운수사  모라      0   10.0    1.1   1
3    4   서당골  모라      0   10.0    1.9   1
4    5    청수  괘법      0   20.0    2.7   1
5    6    사상  괘법      0   10.0    2.2   1
6    7    탑골  괘법      1   10.0    2.6   0
7    8   삼각산  괘법      0   10.0    2.7   1
8    9    괘내  괘법      0   20.0    3.1   1
9   10  황씨묘위  감전      0   10.0    3.1   1
10  11  체육공원  감전      0   20.0    4.0   1
11  12    건강  주례      0   10.0    1.8   1
12  13   백양골  주례      1   10.0    2.8   0
13  14   백양정  주례      0   10.0    7.5   1
14  15   승록정  주례      0   20.0    2.3   0
15  16    복천  주례      0   20.0    2.4   1
16  17    밤골  주례      0   20.0    3.1   1
17  18   삼운정  주례      0   20.0    3.8   1
18  19    무명  주례      0  110.0    0.7   0
19  20    승학  학장      1   65.0    0.3   0
20  21    거북  학장      0   20.0    1.0   1
21  22    백련  엄궁      1   40.0    1.9   0
22  23    불심  엄궁      0   20.0    1.7   1
23  24    승학  엄궁      0   20.0    2.6   1

In [19]:
X = raw_data[['총대장균군','일반세균','질산성질소']]
y = raw_data['적합']

In [20]:
# train_test_split 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, 
                                                   random_state=42)

In [21]:
#  모델 학습 fitting
from sklearn.linear_model import LogisticRegression
model= LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test,y_test)

0.875